version: '2'
services:
 ebot:
   image: hsfactory/ebot
   restart: always
   links:
     - "mysql:mysql"
   ports:
     - "12360:12360"
     - "12361:12361"
     - "12360:12360/udp"
     - "12361:12361/udp"
   networks:
     vpcbr:
   expose:
     - "12360"
   volumes:
     - /opt/docker/ebot/logs:/ebot/logs
     - /opt/docker/ebot/demos:/ebot/demos
   environment:
     EXTERNAL_IP: '192.168.0.59'
     MYSQL_HOST: 'mysql'
     MYSQL_PORT: '3306'
     MYSQL_DB: 'ebotv3'
     MYSQL_USER: 'ebotv3'
     MYSQL_PASS: 'ebotv3'
     LO3_METHOD: 'restart'
     KO3_METHOD: 'restart'
     DEMO_DOWNLOAD: 'true'
     REMIND_RECORD: 'false'
     DAMAGE_REPORT: 'true'
     DELAY_READY: 'false'
     NODE_STARTUP_METHOD: 'node'
     USE_DELAY_END_RECORD: 'true'
     TOORNAMENT_PLUGIN_KEY: ''
     
 ebotweb:
   image: hsfactory/ebotweb
   restart: always
   links:
     - "mysql:mysql"
   ports:
     - "8080:80"
   networks:
     vpcbr:
   volumes:
     - /opt/docker/ebot/demos:/opt/ebot/demos
     - /opt/docker/ebot/logs:/opt/ebot/logs
   environment:
     EBOT_IP: '192.168.0.59'
     EBOT_PORT: '12360'
     EBOT_ADMIN_USER: 'admin'
     EBOT_ADMIN_PASS: 'password'
     EBOT_ADMIN_MAIL: ''
     MYSQL_HOST: 'mysql'
     MYSQL_PORT: '3306'
     MYSQL_DB: 'ebotv3'
     MYSQL_USER: 'ebotv3'
     MYSQL_PASS: 'ebotv3'
     DEMO_DOWNLOAD: 'true'
     DEFAULT_RULES: 'esl5on5'
     TOORNAMENT_ID: ''
     TOORNAMENT_SECRET: ''
     TOORNAMENT_API_KEY: ''
     TOORNAMENT_PLUGIN_KEY: ''

 mysql:
   image: mysql
   restart: always
   volumes:
     - /opt/docker/ebot/mysql:/var/lib/mysql
   ports:
     - "3306:3306"
   networks:
     vpcbr:
   expose:
     - "3306"
   environment:
     - MYSQL_DATABASE=ebotv3
     - MYSQL_USER=ebotv3
     - MYSQL_PASSWORD=ebotv3
     - MYSQL_ROOT_PASSWORD=MyAwesomePassword
     - MYSQL_ROOT_HOST=%
   command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"

 csgo:
    image: mrfoyl/csgoserver:firsttry
    restart: always
    container_name: Csgo-mrfoyl
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    expose:
      - "27015"
    entrypoint:
      - ./csgo.sh
      - -console
      - -usercon
      - +game_type 0
      - +game_mode 1
      - +mapgroup mg_active
      - +map de_cache
      - +hostname "Free-Norwegian-Gameserver"
      - +rcon_password "password"
      - +sv_setsteamaccount INCERT STEAM GAME TOKEN
      - +sv_region 3
      - -net_port_try
      - +logaddress_add ebot:12360


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
